# Generated by Django 5.0.3 on 2024-04-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_category', models.CharField(max_length=50)),
                ('item_price', models.CharField(max_length=50)),
            ],
        ),
    ]
