# Generated by Django 5.0.3 on 2024-05-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmodule', '0005_alter_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
